name: 友联添加申请
description: 在本站添加友联的申请
title: 友联添加申请
body:
- type: checkboxes
  id: agree
  attributes:
    label: 确认
    description: 请确认您满足可添加友联的需求
    options:
      - label: 已了解 https://magma.ink/links/ 中添加站点的需求
        required: true
- type: input
  id: site-name
  attributes:
    label: 站点名称
    description: 你的站点名字
    placeholder: Magma Ink
  validations:
    required: true
- type: input
  id: site-desc
  attributes:
    label: 站点简介
    description: 站点的描述（可选）
    placeholder: 为美好的生活献礼
- type: input
  id: site-link
  attributes:
    label: 站点地址
    description: 站点的主页链接
    placeholder: https://magma.ink
  validations:
    required: true
- type: input
  id: site-img
  attributes:
    label: 站点头像
    description: 你的站点头像链接（推荐）
    placeholder: https://q1.qlogo.cn/g?b=qq&nk=823202450&s=640
